### ISSUE TITLE
Want a link or iframe to wordle

### ISSUE THREAD

**Issue by byronka** [Criyl/yesterdle#1]
I always check yesterdle before playing, so I want to make the transition to playing, with your word already set, as easy as possible.

**Comment by FizleWit** [comment]
Good morning byronka, I am happy to let you know I have just made this feature into a PR! I too enjoy playing Wordle™ in the morning and Yesterdle™ has become a very important part of my workflow, though I could not help but feel that I was wasting time opening both Wordle™ and Yesterdle™ in the browser. Hopefully Criyl can see the value of such a great feature and choose to include it in production! Maybe if all of the users of Yesterdle™ use this new feature and save the 5 seconds of their day after a year I can make back the time I spent on the PR!

**Comment by Criyl** [comment]
This issue has been resolved in PR #3
